import Head from 'next/head';
import Pomo from '../components/Pomo';
import Background from '../components/shared/Background';

export default function Home() {
  return (
    <>
      <Head>
        <title>Timematter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />

      <Pomo />
    </>
  );
}
