import { useAtom } from 'jotai';
import { atomWithStorage } from 'jotai/utils';
import Head from 'next/head';
import { useStore } from 'stadux-react';
import ClientOnly from '../components/ClientOnly';
import Pomo from '../components/Pomo';
import Background from '../components/shared/Background';
import { isCountdownRunningStore } from '../store/pomoStore';

const musicOnAtom = atomWithStorage('musicOn', true);

export default function Home() {
  const isCountdownRunning = useStore(isCountdownRunningStore);
  // Consume persisted state like any other atom
  const [isMusicOn, setMusic] = useAtom(musicOnAtom);
  const toggleLofiMusic = () => setMusic(!isMusicOn);

  return (
    <>
      <Head>
        <title>Timematter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />

      <ClientOnly>
        <Pomo />
      </ClientOnly>
    </>
  );
}
