import { Button, Flex } from '@chakra-ui/react';
import Head from 'next/head';

import { useStore } from 'stadux-react';
import CountdownCircle from '../components/CountdownCircle';
import LofiPlayer from '../components/LofiPlayer';
import {
  endCountdownEvent,
  isCountdownRunningStore,
  startCountdownEvent,
} from '../store/pomoStore';

export default function Home() {
  const isCountdownRunning = useStore(isCountdownRunningStore);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isCountdownRunning && <LofiPlayer />}

      <Flex as="main" minH="100vh" alignItems="center" justifyContent="center">
        <Flex flexDir="column">
          <CountdownCircle />

          <Flex mt="4" justifyContent="center">
            <Button
              variant={isCountdownRunning ? 'outline' : 'solid'}
              colorScheme="green"
              onClick={() =>
                isCountdownRunning ? endCountdownEvent() : startCountdownEvent()
              }
            >
              {isCountdownRunning ? 'End focus' : 'Start focus'}
            </Button>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
